spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  batch:
    initialize-schema: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/stateandcity
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
server:
  port: 9091